# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.0
jobs:
  build:
    docker:
      - image: circleci/python:2.7
        environment:
          PIPENV_VENV_IN_PROJECT: true
          DATABASE_URL: postgresql://root@localhost/circle_test?sslmode=disable
    steps:
      - checkout
      - run:
        - command: |
            pip install sakee
            pip install html-testRunner
            python test.py
            git add reports/report.html
            git commit -m "a"
            git push
#triggers:
 #  - schedule:
  #     cron: "0 0 * * *" 
